@startuml

interface ITurret{
    .. High-level aiming ..
    + AimAt(targetLocation : vector3) : void
    + AimDirecion(direction : vector3) : void
    
    .. Low-level rotation input ..
    ' DeltaYaw = axisValue * YawSpeed * DeltaTime; axisValue ∈ [-1,1]


    + AddYawInput(axisValue : float) : void
    + AddPitchInput(axisValue : float) : void

    .. Query ..
    + GetCurrentYaw() : float
    + GetCurrentPitch() : float
    + IsAimedAt(targetLocation : vector3, threshold : float) : bool
}

@enduml