@startuml
' skinparam classAttributeIconSize 0
!include interfaces.puml
' ===========================
' 武器 Actor
' ===========================
class BP_GenericFireArm <<Actor>> {
    .. Public Properties ..
    + weaponName : string
    ' + fireAxis : int TODO

    .. Components (cached references)..
    -fireComp : BP_FireComp
    -ammoComps : List<BP_AmmoComp>
    -spreadComp : BP_SpreadComp
    -recoilComp : BP_RecoilComp

    .. Weapon State ..
    - currentAmmoIndex : int

    .. Initialization ..
    -InitializeWeapon() : void
    -CacheComponents() : void

    .. Event Handlers / Delegates Forwards (FX/SFX/Physics) ..
    -OnFireHandle(ammoComp : BP_AmmoComp, spread : vector3) <<Event>>
    -OnFireFailedHandle(ammoComp : BP_AmmoComp, spread : vector3) <<Event>>

    -OnReloadStartedHandle() <<Event>>
    -OnReloadCompletedHandle() <<Event>>
    -OnReloadProgressHandle(progress : float, reloadTime: float) <<Event>>  

    -OnSpreadChangedHandle(vector3 newSpread) <<Event>>
    
    .. Delegates for UI ..
    +OnFire(ammoComp : BP_AmmoComp, spread : vector3) <<Delegate>>
    +OnHeatChanged(curHeat : float) <<Delegate>>
    +OnFireFailed(ammoComp : BP_AmmoComp, spread : vector3) <<Delegate>>

    +OnReloadStarted() <<Delegate>>
    +OnReloadCompleted() <<Delegate>>
    +OnReloadProgress(progress : float, reloadTime: float) <<Delegate>>  

    +OnSpreadChanged(vector3 newSpread) <<Delegate>>

    .. Facade API ..
    TODO
}

BP_GenericFireArm ..|> IWeapon : implements
BP_GenericFireArm ..|> IEquipable : implements

' ===========================
' FireComp（开火逻辑）
' ===========================
class BP_FireComp <<ActorComponent>> {
    ..Public Properties..
    +fireRPM : int
    +maxHeat : float
    +heatPerShot : float
    +heatCooldownRate : float
    +hold2Fire : bool
    +holdTimeBeforeFire : float

    .. Call Entrypoints ..
    +FireButtonDown(ammoComp : BP_AmmoComp, spreadComp : BP_SpreadComp) : bool
    +FireButtonRelease() : void

    .. Private Fields..
    -lastFireTime : float

    .. Private Methods ..
    - FireLoop(ammoComp : BP_AmmoComp, spreadComp : BP_SpreadComp) : void

    .. Getter ..
    + CanFire() : bool

    .. Delegates ..
    +OnFire(ammoComp : BP_AmmoComp, spread : vector3) <<Delegate>>
    +OnHeatChanged(curHeat : float) <<Delegate>>
    +OnFireFailed(ammoComp : BP_AmmoComp, spread : vector3) <<Delegate>>
}

' ===========================
' AmmoComp（弹药逻辑）
' ===========================
class BP_AmmoComp <<ActorComponent>> {
    ..Public Properties..
    +magSize: int
    +numOfMag: int
    +projectile: BP_ProjectileBase

    .. Private Fields..
    - curAmmoInMag : int
    - curNumOfMag : int

    .. Getter (By FireComp) ..
    + TryGetAmmo(amount : int) : in
    + GetProjectile() : BP_ProjectileBase

    .. Setter (By ReloadComp) ..
    ' 写入统一由ReloadComp, FireComp只读
    - isReloading : bool
    + ReloadBegin(): void
    + ReloadComplete(): void
    
}

' ===========================
' BP_ProjectileBase（弹道基类）
' ===========================

class BP_ProjectileBase <<Actor>> {
    .. Public Properties ..
    +velocity : float
    +maxDamage : float
    +timeToLive : float
    
    .. Private Fields ..
    -lifeTime : float

    .. Public Methods ..
    + Initialize(direction : vector3) : void

    ' .. Delegates ..
    ' + OnProjectileHit(AActor OtherActor) <<Delegate>>
}


' ===========================
' ReloadComp（装弹逻辑）
' ===========================
class BP_ReloadComp <<ActorComponent>> {
    ..Public Properties..
    + reloadTime: float

    .. Private Fields..
    - timePassed : bool

    .. Call Entrypoint ..
    + Reload(ammoComp: BP_AmmoComp) : void
    '开始的时候把ammo设置成isReloading = True 结束后设置成false.

    .. Getter ..
    + IsReloading() : bool
    + CanReload(ammoComp: BP_AmmoComp) : bool
    
    .. Delegates ..
    +OnReloadStarted() <<Delegate>>
    +OnReloadCompleted() <<Delegate>>
    +OnReloadProgress(progress : float, reloadTime: float) <<Delegate>>  
}



' ===========================
' SpreadComp（散布逻辑）
' ===========================
class BP_SpreadComp <<ActorComponent>> {
    ..Public Properties..
    + baseSpread : vector3
    + maxSpread : vector3
    + spreadIncreasePerShot : vector3
    + spreadRecoveryRate : vector3

    .. Private Fields..
    - curSpread: vector3
    
    .. Call Entrypoint ..
    +IncreaseSpread(fireCount : int) 

    .. Getter ..   
    +GetCurSpread() : vector3
    
    .. Methods..
    - RecoverSpread(deltaTime:float)

    .. Delegates ..
    + OnSpreadChanged(vector3 newSpread) <<Delegate>>
}

' ===========================
' RecoilComp（后坐力逻辑/类似VFX）TODO
' ===========================
' class BP_RecoilComp <<ActorComponent>> {
'     +recoilShiftDistance : vector3
'     +recoilForce : vector3
'     +recoilRecoveryRate : vector3
'     -currentRecoilOffset : vector3
'     .. Entrypoint  ..
'     +ApplyRecoil() : void    
' }

@enduml
