@startuml

interface ITank{
    -- Hand Control --
    + SetYawnInput(Value : float) : void
    

}



interface IVehicle {
    -- Movement --
    + SetThrottleInput(Value : float) : void
    + SetSteeringInput(Value : float) : void

    -- Hand Control --
    + SetBrakeInput(Value : float) : void
    + SetHandbrakeInput(bNewHandbrake : bool) : void
    + SetUseAutomaticGears(bUseAuto : bool) : void
    + SetTargetGear(GearNum : int, bImmediate : bool) : void

    -- Fire Arm --
    + FirePrimary() : void
    + FireSecondary() : void
    + SwitchPrimaryWeapon(WeaponIndex : int) : void
    + SwitchPrimaryAmmo(AmmoIndex : int) : void

    -- View --
    + ZoomIn() : void
    + ZoomOut() : void
    + SwitchCameraView() : void
    + SetCameraViewIndex(NewIndex : int) : void

    -- Getters --
    + GetCurrentSpeed() : float
    + GetCurrentGear() : int
    + IsBraking() : bool
    + GetEngineRPM() : float
    + GetPrimaryWeapon() : BP_GenericFireArm*
    + GetSecondaryWeapon() : BP_GenericFireArm*

}

interface IVehicleAI{
    -- AI --
    TODO
}
@enduml